version: "3.7"

networks:
  traefik-net:
    external: true
    name: traefik-net

volumes:
  foundryvtt-data:
    driver: local
  foundryvtt-core:
    driver: local

services:
  foundryvtt-${FOUNDRYVTT_NAME}:
    image: registry.bvds.fr/foundryvtt:${FOUNDRYVTT_VERSION}
    volumes:
      - foundryvtt-data:/app/foundrydata
      - foundryvtt-core:/app/foundryvtt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.foundryvtt-${FOUNDRYVTT_NAME}.service=foundryvtt-${FOUNDRYVTT_NAME}"
        - "traefik.http.services.foundryvtt-${FOUNDRYVTT_NAME}.loadbalancer.server.port=30000"
        - "traefik.http.routers.foundryvtt-${FOUNDRYVTT_NAME}.rule=Host(`${FOUNDRYVTT_DOMAIN}`)"
        - "traefik.http.routers.foundryvtt-${FOUNDRYVTT_NAME}.entrypoints=websecure"
        - "traefik.http.routers.foundryvtt-${FOUNDRYVTT_NAME}.tls=true"
    networks:
      - traefik-net
