version: '3.7'

services:
    whoami:
        image: traefik/whoami:v1.6.0
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=traefik-frontend"
                - "traefik.http.routers.whoami.service=whoami"
                - "traefik.http.services.whoami.loadbalancer.server.port=80"
                - "traefik.http.routers.whoami.rule: Host(`${DOMAIN}`)"
                - "traefik.http.routers.whoami.entrypoints=websecure"
                - "traefik.http.routers.whoami.tls=true"
                - "traefik.http.routers.whoami.tls.options=intermediate@file"
                - "traefik.http.routers.whoami.middlewares=secure-headers@file"
        networks:
            - traefik-frontend

networks:
    traefik-frontend:
        external: true
        name: traefik-frontend
