version: '3.7'

services:
  redirection-nowww-to-www:
    image: nginx
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.redirect_front_${REDIRECTOR_NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.redirect_front_${REDIRECTOR_NAME}.service=redirect_front_${REDIRECTOR_NAME}"
        - "traefik.http.routers.redirect_front_${REDIRECTOR_NAME}.rule=Host(`${DOMAIN_TO_REDIRECT}`)"
        - "traefik.http.routers.redirect_front_${REDIRECTOR_NAME}.entrypoints=websecure"
        - "traefik.http.routers.redirect_front_${REDIRECTOR_NAME}.tls=true"
        - "traefik.http.middlewares.red-redirect_front_${REDIRECTOR_NAME}.redirectregex.regex=^https://(?:www.)?${DOMAIN_TO_REDIRECT}(.*)"
        - "traefik.http.middlewares.red-redirect_front_${REDIRECTOR_NAME}.redirectregex.replacement=https://www.${DOMAIN_TO_REDIRECT}$${1}"
        - "traefik.http.middlewares.red-redirect_front_${REDIRECTOR_NAME}.redirectregex.permanent=true"
        - "traefik.http.routers.redirect_front_${REDIRECTOR_NAME}.middlewares=red-redirect_front_${REDIRECTOR_NAME}"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
    name: traefik-net
