version: '3.7'

services:

  handbrake:
    image: jlesage/handbrake
    volumes:
      - handbrake-config:/config:rw
      - "$HOME:/storage:ro"
      - "/docker_data/HandBrake/watch:/watch:rw"
      - "/docker_data/HandBrake/output:/output:rw"
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.handbrake.entrypoints=websecure"
        - "traefik.http.routers.handbrake.service=handbrake"
        - "traefik.http.services.handbrake.loadbalancer.server.port=5800"
        - "traefik.http.routers.handbrake.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.handbrake.tls=true"
        - 'traefik.http.routers.handbrake.tls.certresolver=myresolver'

volumes:
  handbrake-config:
    driver: local

networks:
  traefik-net:
    external: true
    name: traefik-net
