version: "3.7"

networks:
  traefik-net:
    external: true
    name: traefik-net
  gitlab-net:
    name: gitlab-net
    driver: overlay

volumes:
  gitlab-data:
    driver: local

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - gitlab-data:/var/opt/gitlab
      - /docker_data/gitlab/logs:/var/log/gitlab
      - /docker_data/gitlab/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gitlab.service=gitlab"
        - "traefik.http.services.gitlab.loadbalancer.server.port=443"
        - "traefik.http.routers.gitlab.rule=Host(`${GITLAB_DOMAIN}`)"
        - "traefik.http.routers.gitlab.entrypoints=websecure"
        - "traefik.http.routers.gitlab.tls=true"
    networks:
      - traefik-net
      - gitlab-net
    secrets:
      - gitlab_root_password

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    networks:
      - gitlab-net
    deploy:
      mode: replicated
      replicas: 1

configs:
  gitlab:
    file: /docker_data/gitlab/host_config/gitlab.rb

secrets:
  gitlab_root_password:
    file: /docker_data/gitlab/secrets/gitlab_root_password
