version: '3.7'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: true
    networks:
      - traefik-net
      - mysql-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
        - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
        - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.phpmyadmin.rule=Host(`${PMA_DOMAIN}`)"
        - "traefik.http.routers.phpmyadmin.tls=true"

networks:
  traefik-net:
    external: true
    name: traefik-net
  mysql-net:
    external: true
    name: mysql-net
