version: '3.7'

services:

  wordpress:
    image: registry.bvds.fr/wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - traefik-net
      - wordpress-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress-${WORDPRESS_NAME}.entrypoints=websecure"
        - "traefik.http.routers.wordpress-${WORDPRESS_NAME}.service=wordpress-${WORDPRESS_NAME}"
        - "traefik.http.services.wordpress-${WORDPRESS_NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.wordpress-${WORDPRESS_NAME}.rule=Host(`${WORDPRESS_DOMAIN}`)"
        - "traefik.http.routers.wordpress-${WORDPRESS_NAME}.tls=true"
        - 'traefik.http.routers.wordpress-${WORDPRESS_NAME}.tls.certresolver=myresolver'

  db:
    image: registry.bvds.fr/mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress-db-data:/var/lib/mysql
    networks:
      - wordpress-net
      - mysql-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  wordpress-data:
    driver: local
  wordpress-db-data:
    driver: local

networks:
  wordpress-net:
    driver: overlay
    name: wordpress-${WORDPRESS_NAME}-net
  traefik-net:
    external: true
    name: traefik-net
  mysql-net:
    external: true
    name: mysql-net
