version: '3.7'

services:
  mailserver:
    image: registry.bvds.fr/tvial-docker-mailserver
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
      # POP3S
      #- target: 995
      #  published: 995
      #  protocol: tcp
      #  mode: host
    volumes:
      - mailserver-maildata:/var/mail
      - mailserver-mailstate:/var/mail-state
      - /docker_data/mail/docker-mailserver/config:/tmp/docker-mailserver
      - /docker_data/main/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    environment:
      - OVERRIDE_HOSTNAME="${HOSTNAME}.${MAIN_SLD}"
      - OVERRIDE_DOMAINNAME="${HOSTNAME}.${MAIN_SLD}"
      - DMS_DEBUG=0
      - ONE_DIR=1
      - POSTMASTER_ADDRESS="postmaster@${MAIN_SLD}"
      - PERMIT_DOCKER=network
      - NETWORK_INTERFACE=
      - TLS_LEVEL=
      - SPOOF_PROTECTION=
      - ENABLE_SRS=0
      - ENABLE_POP3=
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_MANAGESIEVE=
      - POSTSCREEN_ACTION=enforce
      - SMTP_ONLY=
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN="*.${MAIN_SLD}"
      - VIRUSMAILS_DELETE_DELAY=
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
      - POSTFIX_DAGENT=
      - POSTFIX_MAILBOX_SIZE_LIMIT=
      - POSTFIX_MESSAGE_SIZE_LIMIT=
      - PFLOGSUMM_TRIGGER=
      - PFLOGSUMM_RECIPIENT=
      - PFLOGSUMM_SENDER=
      - LOGWATCH_INTERVAL=
      - LOGWATCH_RECIPIENT=
      - REPORT_RECIPIENT=0
      - REPORT_SENDER=
      - REPORT_INTERVAL=daily
      - POSTFIX_INET_PROTOCOLS=all
      - ENABLE_SPAMASSASSIN=0
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - MOVE_SPAM_TO_JUNK=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=6.31
      - SA_SPAM_SUBJECT=***SPAM*****
      - ENABLE_FETCHMAIL=0
      - FETCHMAIL_POLL=300
      - ENABLE_LDAP=
      - LDAP_START_TLS=
      - LDAP_SERVER_HOST=
      - LDAP_SEARCH_BASE=
      - LDAP_BIND_DN=
      - LDAP_BIND_PW=
      - LDAP_QUERY_FILTER_USER=
      - LDAP_QUERY_FILTER_GROUP=
      - LDAP_QUERY_FILTER_ALIAS=
      - LDAP_QUERY_FILTER_DOMAIN=
      - DOVECOT_TLS=
      - DOVECOT_USER_FILTER=
      - DOVECOT_PASS_FILTER=
      - DOVECOT_MAILBOX_FORMAT=maildir
      - DOVECOT_AUTH_BIND=
      - ENABLE_POSTGREY=0
      - POSTGREY_DELAY=300
      - POSTGREY_MAX_AGE=35
      - POSTGREY_TEXT=Delayed by postgrey
      - POSTGREY_AUTO_WHITELIST_CLIENTS=5
      - ENABLE_SASLAUTHD=0
      - SASLAUTHD_MECHANISMS=
      - SASLAUTHD_MECH_OPTIONS=
      - SASLAUTHD_LDAP_SERVER=
      - SASLAUTHD_LDAP_SSL=
      - SASLAUTHD_LDAP_BIND_DN=
      - SASLAUTHD_LDAP_PASSWORD=
      - SASLAUTHD_LDAP_SEARCH_BASE=
      - SASLAUTHD_LDAP_FILTER=
      - SASLAUTHD_LDAP_START_TLS=
      - SASLAUTHD_LDAP_TLS_CHECK_PEER=
      - SASL_PASSWD=
      - SRS_SENDER_CLASSES=envelope_sender
      - SRS_EXCLUDE_DOMAINS=
      - SRS_SECRET=
      - DEFAULT_RELAY_HOST=
      - RELAY_HOST=
      - RELAY_PORT=25
      - RELAY_USER=
      - RELAY_PASSWORD=
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      
  webmail-rainloop:
    image: hardware/rainloop
    depends_on:
      - mailserver
    volumes:
      - webmail-rainloop-data:/rainloop/data
    networks:
      - traefik-net
      - internal
      - rainloop-nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rainloop.entrypoints=websecure"
        - "traefik.http.routers.rainloop.service=webmail-rainloop-nginx"
        - "traefik.http.services.webmail-rainloop-nginx.loadbalancer.server.port=8888"
        - "traefik.http.routers.rainloop.rule=Host(`${WEBMAIL_DOMAIN}`)"
        - "traefik.http.routers.rainloop.tls=true"

volumes:
  mailserver-mailstate:
    driver: local
  mailserver-maildata:
    driver: local
  webmail-rainloop-data:
    driver: local

networks:
  traefik-net:
    external: true
    name: traefik-net
  rainloop-nginx:
    driver: overlay
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.2.0/24
